[loggers]
keys=root, notification, auto_activer, kakaotalk_parser, discord_bot, openai

[handlers]
keys=stream_handler, file_handler

[formatters]
keys=default_formatter

[logger_root]
level=INFO
handlers=stream_handler, file_handler

[logger_notification]
level=DEBUG
handlers=stream_handler, file_handler
qualname=notification
propagate=0

[logger_auto_activer]
level=DEBUG
handlers=stream_handler, file_handler
qualname=auto_activer
propagate=0

[logger_kakaotalk_parser]
level=DEBUG
handlers=stream_handler, file_handler
qualname=kakaotalk_parser
propagate=0

[logger_discord_bot]
level=DEBUG
handlers=stream_handler, file_handler
qualname=discord_bot
propagate=0

[logger_openai]
level=DEBUG
handlers=stream_handler, file_handler
qualname=openai
propagate=0

[handler_stream_handler]
class=StreamHandler
level=NOTSET
formatter=
args=(sys.stdout,)

[handler_file_handler]
class=FileHandler
level=NOTSET
formatter=default_formatter
args=('./logs/output.log', 'a')

[formatter_default_formatter]
format=|%(asctime)s|%(name)s|%(levelname)s| - %(message)s
datefmt=%Y-%m-%d %H:%M:%S